# Generated by Django 5.1.1 on 2024-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.URLField(),
        ),
    ]
