# Generated by Django 5.1.1 on 2024-11-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0013_alter_category_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
